name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker login
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        shell: bash
        run: docker login --username ${USERNAME} --password ${PASSWORD}

      - name: Docker build
        shell: bash
        run: |
          docker build . --tag siku2/balena-airthingswave
          docker push siku2/balena-airthingswave
