name: Release branch docker image
on: push

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Available platforms
      run: echo "${{ steps.buildx.outputs.platforms }}"

    - name: Login to Docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash
      run: docker login --username ${USERNAME} --password ${PASSWORD}

    - name: Build image
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
          --push \
          --tag siku2/balena-airthingswave:${GITHUB_REF##*/} \
          .
