name: Release branch docker image
on: push

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Print available platforms
      run: echo "${{ steps.buildx.outputs.platforms }}"

    - name: Login to Docker
      run: docker login --username ${USERNAME} --password ${PASSWORD}
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
          --push \
          --tag siku2/balena-airthingswave:${GITHUB_REF##*/} \
          .
